name: Publish Docker Image

on:
  push:
    branches:
      - '**'
  release:
    types:
      - published

jobs:
  build:
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Repo
        uses: actions/checkout@v4

      - name: Check Free Space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          df -Th

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Determine Docker Tag
        run: |
          if [ "${{ github.event_name }}" == "release" ]; then
            TAG=${{ github.event.release.tag_name }}
          else # it's a branch
            if [ "${{ github.ref_name }}" == "main" ]; then
              TAG=latest
            else
              BRANCH_NAME="${{ github.ref_name }}"
              TAG=$(echo "$BRANCH_NAME" | cut -d'-' -f1)
            fi
          fi
          TAG=$(echo $TAG | sed 's/[^a-zA-Z0-9.]/-/g' | tr '[:upper:]' '[:lower:]')
          echo "Determined TAG: $TAG"
          echo "TAG=$TAG" >> $GITHUB_ENV

      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          tags: muhac/jupyter-pytorch:${{ env.TAG }}
          push: true

      - name: Check Free Space Remaining
        run: df -Th
